KonferansPortal/Models/Konferans.cs
namespace KonferansPortal.Models
{
    public class Konferans
    {
        public string Name { set; get; }
        public int Id { set; get; }
        public string Description { set; get; }
        public int Price { set; get; }
        public List<Uye> Katilimcilar { set; get; } = new List<Uye>();
        public List<Egitmen>? Egitmenler { set; get; }
        public DateTime StartDate { set; get; }
        public DateTime EndDate { set; get; }
        public string? ImageUrl { set; get; }
        public List<Paylasim>? Paylasimlar { set; get; }
        public List<Tartisma>? Tartismalar { set; get; }

        public List<OnKayit>? OnKayitListe { set; get; }
        public int Capacity { get; set; } = int.MaxValue;
        public byte[]? KonferansImage { set; get;  }
    }
}

KonferansPortal/Controllers/KonferansController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KonferansPortal.Data;
using KonferansPortal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.Extensions.Hosting;
using System.Dynamic;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Security.Policy;
using System.Text.Json.Serialization;
using System.Text.Json;

namespace KonferansPortal.Controllers
{
    public class KonferansController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<Uye> _userManager;

        public KonferansController(AppDbContext context, IAuthorizationService authorizationService, UserManager<Uye> userManager)
        {
            _context = context;
            _authorizationService = authorizationService;
            _userManager = userManager;
        }

        // GET: Konferans
        public async Task<IActionResult> Index()
        {
            return View(await _context.Konferanslar.ToListAsync());
        }
        // GET: Konferans/Create
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Konferans/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Konferans konferans, IFormFile file)
        {
            konferans.KonferansImage = file != null ? GetByteArrayFromFile(file) : null;
            if (ModelState.IsValid)
            {
                _context.Add(konferans);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(konferans);
        }

        // GET: Konferans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var result = await CheckClaims((int)id);
            var currentUser = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            await _userManager.AddClaimsAsync(currentUser, result);
            var konferans = await _context.Konferanslar.Include(k => k.Katilimcilar).Include(k => k.Egitmenler)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (result == null || konferans == null)
            {
                return NotFound();
            }

            return View(konferans);
        }

        [HttpGet]
        public async Task<IActionResult> KayitOl(int id)
        {
            var konferans = await _context.Konferanslar.Include(k => k.Katilimcilar).Include(konferans => konferans.OnKayitListe).ThenInclude(o => o.uye).FirstOrDefaultAsync(k => k.Id == id);

            var currentUser = await _context.Uyeler.Include(u => u.katilinanKonferanslar).FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            if (currentUser != null)
            {
                if (konferans.Katilimcilar == null)
                {
                    konferans.Katilimcilar = new List<Uye>();
                }

                else if (konferans.Katilimcilar.Any(k => k.Email == currentUser.Name))
                {
                    return RedirectToAction("KonferansMainView", new { id = id });
                }
                OnKayit onKayit = new OnKayit
                {
                    uye = currentUser,
                    dekontFile = null,
                    isPaid = false,
                    isChecked = false,
                    konferans = konferans
                };
                konferans.OnKayitListe.Add(onKayit);
                if (currentUser.onKayitKonferanslar == null)
                {
                    currentUser.onKayitKonferanslar = new List<OnKayit>();
                }
                currentUser.onKayitKonferanslar.Add(onKayit);
                await _context.SaveChangesAsync();
                return View();
            }
            return RedirectToAction("Login", "Uye");
        }


        [HttpGet]
        [Authorize(Policy = "IsEgitmenOrKatilimci")]
        public async Task<IActionResult> KonferansMainView(int id)
        {
            
            var konferans = await _context.Konferanslar.Include(k => k.Paylasimlar).FirstOrDefaultAsync(k => k.Id == id);

            if (konferans == null)
            {
                return NotFound();
            }
            

            return View(konferans);
        }

        [HttpGet]
        [Authorize(Policy = "IsEgitmenOrKatilimci")]
        public async Task<IActionResult> KatilimcilarListView(int id)
        {
            var result = await _context.Konferanslar
                .Include(k => k.Katilimcilar)
                .Include(k => k.Egitmenler)
                .ThenInclude(e => e.UyeModel)
                .FirstOrDefaultAsync(k => k.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }


        

        [Authorize(Policy = "IsEgitmen")]
        public IActionResult PaylasimEkle(int id)
        {
            return View();
        }

        [Authorize(Policy = "IsEgitmen")]
        [HttpPost]
        public async Task<IActionResult> PaylasimEkle(int id, string Title, string? Content, IFormFile file)
        {
            var paylasim = new Paylasim
            {
                Title = Title,
                Content = Content,
                ContentFile = file != null ? GetByteArrayFromFile(file) : null,
                Date = DateTime.Now,
                Publisher = _context.Uyeler.FirstOrDefault(u => u.Email == User.Identity.Name),
                Extension = System.IO.Path.GetExtension(file.FileName),
                PaylasilanKonferans = await _context.Konferanslar.FirstAsync(k => k.Id == id)
            };
            var result = await _context.Konferanslar.Include(k => k.Paylasimlar).FirstAsync(k => k.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            if (result.Paylasimlar == null)
            {
                result.Paylasimlar = new List<Paylasim>();
            }
            result.Paylasimlar.Add(paylasim);
            _context.Konferanslar.Update(result);

            await _context.SaveChangesAsync();
            var res= await CheckClaims((int)id);
            var currentUser = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            await _userManager.AddClaimsAsync(currentUser, res);
            return RedirectToAction("KonferansMainView", new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> GetPaylasimFile(int konferansid, int paylasimid)
        {
            var konferans = await _context.Konferanslar.Include(k => k.Paylasimlar).FirstOrDefaultAsync(k => k.Id == konferansid);
            if (konferans != null && konferans.Paylasimlar != null && konferans.Paylasimlar.FirstOrDefault(p => p.Id == paylasimid) != null)
            {
                var paylasim = konferans.Paylasimlar.FirstOrDefault(p => p.Id == paylasimid);

                if (paylasim != null && paylasim.ContentFile != null)
                {
                    return File(paylasim.ContentFile, "application/octet-stream", "paylasim" + paylasimid + paylasim.Extension);
                }
            }
            return null;

        }


        public async Task<string> DownloadPaylasimFile(int paylasimid, int konferansid)
        {

            var url = Url.Action("GetPaylasimFile", "File", new { paylasimid = paylasimid }, Request.Scheme);
            if(url != null)
                return url;
            return null;

        }
        private byte[] GetByteArrayFromFile(IFormFile file)
        {
            using (var target = new MemoryStream())
            {
                file.CopyTo(target);
                return target.ToArray();
            }
        }

        /*public void dosyaIndir()
        {

        }*/
        [HttpGet]
        public IActionResult CreateTartisma(int id)
        {
            var model = new TartismaViewModel
            {
                KonferansId = id
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTartisma(TartismaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _context.Uyeler.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
                var konferans = await _context.Konferanslar.Include(k => k.Tartismalar).FirstOrDefaultAsync(k => k.Id == model.KonferansId);
                if (konferans == null)
                {
                    return NotFound();
                }

                var tartisma = new Tartisma
                {
                    Title = model.Title,
                    Content = model.Content,
                    Date = DateTime.Now,
                    Publisher = currentUser,
                    Konferans = konferans,
                    Id = null
                };

                var result = _context.Add(tartisma);
                await _context.SaveChangesAsync();
                var konferanss = await _context.Konferanslar.Include(k => k.Tartismalar).FirstOrDefaultAsync(k => k.Id == model.KonferansId);
                if (konferanss.Tartismalar == null)
                {
                    konferanss.Tartismalar = new List<Tartisma>();
                }
                konferanss.Tartismalar.Add(result.Entity);
                _context.Konferanslar.Update(konferanss);
                await _context.SaveChangesAsync();
                return RedirectToAction("Tartismalar", new { konferansId = model.KonferansId });
            }

KonferansPortal/Views/Konferans/Create.cshtml
@model KonferansPortal.Models.Konferans

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Konferans</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Resim</label>
                <input id="fileSelector" type="file" name="file" class="form-control-file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>
    function importToHidden() {
        document.getElementById('hiddenInput').value = document.getElementById('fileSelector').value;
    }
</script>

KonferansPortal/Views/Konferans/CreateTartisma.cshtml
@model KonferansPortal.Models.TartismaViewModel

@{
    ViewData["Title"] = "CreateTartisma";
}

<h1>Tartışma Oluştur</h1>

<h4>Tartisma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTartisma" method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <input asp-for="KonferansId" type="hidden" class="form-control" value="@Model.KonferansId"/>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KonferansPortal/Views/Konferans/Delete.cshtml
@model KonferansPortal.Models.Konferans

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Konferans</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KonferansPortal/Views/Konferans/Details.cshtml
@model KonferansPortal.Models.Konferans

@{
    ViewData["Title"] = "Details";
    var isUye = User.Identity.IsAuthenticated;
    var isEgitmenOrKatilimci = User.HasClaim(c => c.Type == "IsEgitmenOrKatilimci" && (c.Value == "True" || c.Value == "true"));
    var isOnKayit = User.HasClaim(c => c.Type == "IsOnKayitli" && (c.Value == "True" || c.Value == "true"));
}

<h1>Details</h1>

<div>
    <h4>Konferans</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        @if (Model.Capacity > Model.Katilimcilar.Count + Model.OnKayitListe.Count){
            if (isUye && !isEgitmenOrKatilimci && !isOnKayit)
            {
                <dd class="col-sm-10">
                    <a class="nav-link text-dark" asp-action="KayitOl" asp-route-id="@Model.Id">Kayıt Ol</a>
                </dd>
            }
            else if (isUye && isEgitmenOrKatilimci )
            {
                <dd>
                    <a class="nav-link text-dark" asp-action="KonferansMainView" asp-route-id="@Model.Id" class="form-inline">Konferans Sayfasına Git</a>
                </dd>
            }
            else if (isUye && isOnKayit)
            {
                <dd class="col-sm-10">
                    <form id="form" name="form" enctype="multipart/form-data" method="post" asp-action="DekontYukle" asp-route-konferansId="@Model.Id">
                        <input id="file" type="file" name="file" class="form-control" />
                        <button type="submit">Dekont Yükle</button>
                    </form>
                    <button class="nav-link text-dark" onclick = "kayitSil()">Kayıt Sil</button>
                </dd>
            }
            else{
                <dd class="col-sm-10">
                    <a class="nav-link text-dark" asp-controller="Uye" asp-action="Register">Kayıt Ol</a>
                </dd>
            }
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    <script>
        async function dosyaYukle() {
            const form = document.getElementById('fileSelector');
            if (form != null) {
                //const formData = new FormData(form.files[0]);
                const response = await fetch(`/Konferans/DekontYukle?konferansId=${@Model.Id}`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/octet-stream'
                    },
                    body: form.files[0].
                });
                const data = await response.json();
                if (data != null)
                    alert("Dekont Yüklenmiştir");
                else
                    alert("Hata! Dekont Yüklenemedi!");
            }
            else
                alert("Dosya seçin")
        
        }

        async function kayitSil() {
            const response = await fetch(`/Uye/OnKayitSil?konferansId=${selected}`);
            const data = await response.json();
            if (!alert('Ön Kayıdınız Silinmiştir')) { window.location.reload(); }
        }

    </script>
}

KonferansPortal/Views/Konferans/Edit.cshtml
@model KonferansPortal.Models.Konferans

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Konferans</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KonferansPortal/Views/Konferans/Index.cshtml
@model List<KonferansPortal.Models.Konferans>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <tbody>
        @foreach (var item in Model) {
            <tr onclick="window.location.href='@Url.Action("Details", "Konferans", new { id = item.Id })'" style="cursor: pointer;">
                <td>
                    <div>
                        <img src="@item.ImageUrl" alt="@item.Name" style="max-width: 100px; max-height: 100px;" />
                    </div>
                </td>

                <td>
                    <div>
                        <h4>@item.Name</h4>
                        <h5>@item.Description</h5>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

KonferansPortal/Views/Konferans/KatilimcilarListView.cshtml
@model Konferans

@{
    ViewData["Title"] = "KatilimcilarListView";
}
<h2>@Model.Name</h2>

<table class="table">
    <tbody>
        <h3>Eğitmenler</h3>
        @if (Model.Egitmenler != null)
        {
            @foreach (var item in Model.Egitmenler)
            {
                <tr>
                    <td>
                        <div>
                            <h4>@item.UyeModel.Name @item.UyeModel.Surname</h4>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<table class="table">
    <tbody>
        <h3>Katılımcılar</h3>
        @if(Model.Katilimcilar != null)
        {
            @foreach (var item in Model.Katilimcilar)
            {
                <tr>
                    <td>
                        <div>
                            <h4>@item.Name @item.Surname</h4>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

KonferansPortal/Views/Konferans/KayitOl.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h4>Kayıt işleminiz alınmıştır</h4>

KonferansPortal/Views/Konferans/KonferansMainView.cshtml
@model KonferansPortal.Models.Konferans

@{
    ViewData["Title"] = "KonferansMainView";
}

<h1>@Model.Name</h1>

<div>
    <ul>
        <li><a class="nav-link text-dark" asp-action="KatilimcilarListView" asp-route-id="@Model.Id">Katılımcılar</a></li>
        <li><a class="nav-link text-dark" asp-action="Tartismalar" asp-route-id="@Model.Id">Tartışmalar</a></li>
    </ul>
</div>

<div>
    @if (User.Identity.IsAuthenticated && User.HasClaim(c => c.Type == "IsEgitmen" && c.Value == "True"))
    {
        <a asp-action="PaylasimEkle" asp-route-id="@Model.Id">Paylaşım Ekle</a>
    }
    <table class="table">
        <tbody>
            @if (Model.Paylasimlar != null)
                @foreach (var item in Model.Paylasimlar)
                {
                    <tr onclick="window.location.href='@Url.Action("PaylasimDetails", "Konferans", new { pId = item.Id , kId=Model.Id })'">

                        <td>
                            <div>
                                <h4>@item.Title</h4>
                                <h5>@item.Content</h5>
                                <h6>@item.Publisher</h6>
                                <h6>@item.Date</h6>
                                @if(item.ContentFile != null)
                                {
                                    <a href="/Konferans/DownloadPaylasimFile?paylasimid=@item.Id&konferansid=@Model.Id">Dosya</a>
                                }
                            </div>
                        </td>
                    </tr>
                }
        </tbody>
    </table>
</div>

<script>
    async function openFileInNewTab(paylasimid, konferansid) {
        const response = await fetch(`/Konferans/DownloadPaylasimFile?paylasimid=${paylasimid}&konferansid=${konferansid}`);
        const url = await response.text();

        if (url) {
            window.open(url, '_blank');
        } else {
            alert('File not found');
        }
    }
</script>

KonferansPortal/Views/Konferans/PaylasimDetails.cshtml
@model KonferansPortal.Models.Paylasim


<h1>@Model.Title</h1>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Title
        </dt>
        <dd class="col-sm-10">
            @Model.Title
        </dd>
        <dt class="col-sm-2">
            Content
        </dt>
        <dd class="col-sm-10">
            @Model.Content
        </dd>
        <dt class="col-sm-2">
            Date
        </dt>
        <dd class="col-sm-10">
            @Model.Date.ToString("yyyy-MM-dd HH:mm:ss")
        </dd>
        <dt class="col-sm-2">
            Publisher
        </dt>
        <dd class="col-sm-10">
            @Model.Publisher.UserName
        </dd>
        @if(Model.ContentFile != null)
        {
            <dt class="col-sm-2">
                Dosya
            </dt>
            <dd class="col-sm-10">
                <a href="/Konferans/DownloadPaylasimFile?paylasimid=@Model.Id&konferansid=@Model.PaylasilanKonferans.Id">Dosya</a>
            </dd>
        }
    </dl>
</div>

<h4>Yorumlar</h4>
<hr />
@if (Model.Yorumlar != null && Model.Yorumlar.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Yazar
                </th>
                <th>
                    Yorum
                </th>
                <th>
                    Tarih
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var yorum in Model.Yorumlar)
            {
                <tr>
                    <td>
                        @yorum.Publisher.Name @yorum.Publisher.Surname
                    </td>
                    <td>
                        @yorum.Content
                    </td>
                    <td>
                        @yorum.Date.ToString("yyyy-MM-dd HH:mm:ss")
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Yorum bulunamadı.</p>
}

<div class="comment-form">
    <form asp-action="AddCommentTartisma" asp-route-TartismaId="@Model.Id" method="post">
        <textarea name="yorumYazi" placeholder="Yorumunuz..." required></textarea>
        <button type="submit">Yorum Ekle</button>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KonferansPortal/Views/Konferans/PaylasimEkle.cshtml
@model KonferansPortal.Models.Paylasim
@{
}

<h1>PaylasimEkle</h1>
<form method="post" asp-action="PaylasimEkle" enctype ="multipart/form-data">
    <div>
        <label asp-for="Title">Başlık</label>
        <input asp-for="Title" />
    </div>
    <div>
        <label asp-for="Content">İçerik</label>
        <input asp-for="Content" />
    </div>
    <div>
        <label>Dosya</label>
        <input id="fileSelector" type="file" name="file" class="form-control-file" onchange="importToHidden()" />
    </div>
    <button type="submit">Paylaşım Ekle</button>
</form>